### ISSUE TITLE
Fix: Failure while translating Erlang's logger event

### ISSUE THREAD

**Issue by masonforest** [mana-ethereum/mana#492]
Currently if you log into the PoA test server and run `sync_with_infura` on master you get the following error:

```
17:02:39.121 [error] Failure while translating Erlang's logger event
** (UndefinedFunctionError) function Logger.Translator.translate/4 is undefined (module Logger.Translator is not available)
    (logger) Logger.Translator.translate(:debug, :error, :report, {{:erl_prim_loader, :file_error}, 'File operation error: emfile. Target: /usr/local/lib/elixir/bin/../lib/elixir/ebin/Elixir.Exception.beam. Function: get_file. Process: code_server.'})
    (logger) lib/logger/erlang_handler.ex:104: Logger.ErlangHandler.translate/6
    (logger) lib/logger/erlang_handler.ex:97: Logger.ErlangHandler.translate/5
    (logger) lib/logger/erlang_handler.ex:27: anonymous fn/3 in Logger.ErlangHandler.log/2
    (logger) lib/logger.ex:861: Logger.normalize_message/2
    (logger) lib/logger.ex:684: Logger.__do_log__/3
    (kernel) logger_backend.erl:51: :logger_backend.call_handlers/3
    (kernel) logger_backend.erl:38: :logger_backend.log_allowed/2

** (EXIT from #PID<0.91.0>) an exception was raised:
    ** (UndefinedFunctionError) function Exception.blame/3 is undefined or private
        (elixir) Exception.blame(:error, :undef, [{Exception, :normalize, [:error, {:badmatch, {:error, :emfile}}, []], []}, {Mix.CLI, :run_task, 2, [file: 'lib/mix/cli.ex', line: 83]}, {:elixir_compiler, :dispatch, 4, [file: 'src/elixir_compiler.erl', line: 71]}, {:elixir_compiler, :compile, 3, [file: 'src/elixir_compiler.erl', line: 68]}, {:elixir_lexical, :run, 2, [file: 'src/elixir_lexical.erl', line: 17]}, {:elixir_compiler, :quoted, 2, [file: 'src/elixir_compiler.erl', line: 23]}, {Code, :require_file, 2, [file: 'lib/code.ex', line: 767]}, {Kernel.CLI, :wrapper, 1, [file: 'lib/kernel/cli.ex', line: 503]}])
        (elixir) lib/kernel/cli.ex:75: Kernel.CLI.format_error/3
        (elixir) lib/kernel/cli.ex:157: Kernel.CLI.print_error/3
        (elixir) lib/kernel/cli.ex:119: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

Note that if you sync from scratch the error goes away.

This may just be because our state is getting so large.

**Comment by hayesgm** [comment]
which aspects of state will get larger as we sync more blocks. I could imagine the merkle trie and it's storage in rocks db, but anything else?

**Comment by hayesgm** [comment]
Closing does not appear to be happening on current PoA test server
